### PR TITLE
23_ReactIntegration

### PR DESCRIPTION
**Pull request by kevintamakuwala**
Minor bug fix: 
- Removed build from .gitignore
- built the project

This should work now, it is working on test env

### CODE REVIEW

**Review by Nisarg155 — APPROVED** [review]

**Comment by Nisarg155** [comment]
@kevintamakuwala  it working !! 
issue no #23

**Comment by kevintamakuwala** [comment]
Just one suggestion, documentation needs to be improved.

**Comment by Nisarg155** [comment]
what changes should be made ? 
Can you elaborate...

**Comment by kevintamakuwala** [comment]
Like follow standard practices of writing documentation. eg: 
- Description of project should be very precise and short. 
- Write certain guidelines of maintaining folder structure and code quality. 
- Impose necessary checks on PRs.
- Give entire workflow of creating React Component (which i mentioned) along with workflow of HTML. 
-  Readme should include only important and necessary information and no jargons.

Besides,
- Like you have mentioned tech stacks in Readme, integrate all of them with HTML project (very difficult for new commers). I did it for React.
- Provide guidelines for production and building projects.

You can raise an issue for improving documentations and make it as good-first-issue.

**Pull request merged**
