### PR TITLE
React Setup and Autoplay Slider component in React.

### PR DESCRIPTION
**Pull request by kevintamakuwala**
# Features:
- Implemented Autoplay Slider with swiping functionality using React. Can be easily configured with cards, images and other components.
- Created React set-up under components directory, wherein all the react components for the web application can reside.
- Changed the components url in script.js file to absolute instead of relative, which also adds up in hosting React or any other framework on other Port Number. In this, way HTML and React Components are being linked.

# Important - to be included in project README
- To run React Components: go to "react-components" directory and start the react project using `npm start`. This will start React on port 3000 and HTML is live on another port number. 
- Add a new component in pages folder under `react-components > src > pages` directory, also add required routes in app.js and Layout.jsx for navigation.

### CODE REVIEW

**Comment by Rushi0508** [comment]
@kevintamakuwala as you know our repo is hosted on github pages, so have you made the configurations so that the react components can be viewed ?

**Review by Rushi0508 — COMMENTED** [review]
@kevintamakuwala as you know our repo is hosted on github pages, so have you made the configurations so that the react components can be viewed ?

**Review by Rushi0508 — APPROVED** [review]
Seems Good!! Thanks @kevintamakuwala for your valuable contribution.

**Comment by kevintamakuwala** [comment]
# Setup for React based applications.
Instead of using Conventional React-Router-Dom, I have used Query Params for routing two different Components.
- I have used React Static Build to serve static files in GitHub Pages.
- As build folder is converted in raw Html, CSS and JS, they can be easily rendered by Github actions as it is considered in HTML format.
- I have used query parameters in the url for react components. eg for Slider component URL will be: **`http://127.0.0.1:5500//components/react/build/?slider`** Which is the best possible way of configuration in Github Pages.
### Important Guidelines to be included in README.md
- For creating a new React Component, include relative url in components.json in the format:
 `/components/react/build/?<component-name>` also include in `app.js > path object` as `<component-name>:<Component/>` (Refer app.js and components.json file).
- Before making a commit, make sure to build the react project explicitly, as For Github pages: Static build is required.
command: `npm run build`


Let me know, if any issue persists 👍 :)

**Comment by Rushi0508** [comment]
It shows error in live website. Please, look into it.

**Comment by kevintamakuwala** [comment]
I think there may be some issues in the workflows as login and contact links are also dead. It is working completely fine on my local machine with same code.
There should be no problems with the react configuration as static build is involved. Still, I will look out for some defects. But I highly suggest moving the current project into a specific technology, like make it purely HTML or purely react based.
Besides, I will figure out a way, if you find any issues with the workflows, please correct it.

**Comment by Rushi0508** [comment]
I found that github's dependabot is giving two security issues related to versions, so I think this may be the issue. Try to figure it out and we are also working to figure this out. If it's not possible to solve the issue, unfortunately we have to revert the PR.

**Comment by kevintamakuwala** [comment]
Ok, trying to resolve. Need some time, will let you know the final status

**Comment by kevintamakuwala** [comment]
I have solved the issue, it is working perfectly fine. Please reopen the PR so I could commit.

**Comment by Rushi0508** [comment]
Merged PR can't be re-opened. You can place a new PR or I need to revert this and them proceed with new. So tell me should I revert this or you are placing a new PR ?

**Comment by kevintamakuwala** [comment]
Ohh ok, i am placing a new PR.

**Pull request merged**
