### PR TITLE
23 kevintamakuwala

### PR DESCRIPTION
**Pull request by kevintamakuwala**
All the urls are working fine.

#### To create a new component follow these steps:
- Go to package.JSON file and replace the _**homepage url**_ `https://csiddu.github.io/Frontend-Treasure/components/react/build/` with `http://127.0.0.1:5500/components/react/build/` i.e your live server url followed by  `components/react/build/`. This is necessary as Production Url has to be replaced with Live Server's IP.
- Make an entry in **App.js > path** object eg: `<component-name>: <Component/>`
- Make an entry for url in components.JSON. eg: `react/build/?<component-name>`
- Make an entry for url in Layout.jsx. For local development use: `/components/react/build/?<component-name>` and before committing make it to `/Frontend-Treasure/components/react/build/?<component-name>`. This is because repo name should be included for github pages deployment.
- Finally add your component card in components.html.
- #### Note: During development, if your code doesn't work, make sure to build react app. If still any issue persists, read the steps again.
- ### Before committing:

1. Always explicitly, **build the react project, every-time before committing** `npm run build`. Only then your changes will be reflected in static build.
2. Make sure the Urls in package.json and Layout.jsx are production friendly, as mentioned earlier. (Refer code for more understanding).

### CODE REVIEW

**Review by Nisarg155 — APPROVED** [review]

**Comment by kevintamakuwala** [comment]
@Nisarg155 please revert this commit, there is some issue in react rendering for this repository. In my testing environment it is working perfectly fine: https://kevintamakuwala.github.io/Test-Treasure/components/react/build/?slider

**Comment by Nisarg155** [comment]
okay

**Comment by Nisarg155** [comment]
should i reset the branch to the last commit

**Comment by kevintamakuwala** [comment]
Yes, but leave it I have created a new branch and raised a PR. Merge that it is working on Test env.

**Pull request merged**
